version: "3.9"

services:
  spider:
    build:
      context: .
    volumes:
      - .:/goal
    command: >
      sh -c " scrapy crawl theguardian &&
              scrapy crawl goal && 
              scrapy crawl ndtv 
            "
    environment:
      - SCRAPER_ARGS=
